### ISSUE TITLE
Add UI to select image from multiple services

### ISSUE THREAD

**Issue by bengott** [bengott/meteor-avatar#10]
Provide UI that allows user to select avatar image from all linked services (twitter, facebook, etc.). Custom (uploaded) image could also be handled from within this UI workflow. I'll work on some mockups for this...

**Comment by rvanhoepen** [comment]
Any plans on how this should be implemented? This will depend on the developer's ability to have the user link multiple accounts. and in some cases unless the user specifies additional profile detail and doesn't link any additional accounts this might not even be relevant (eg. if the user signs up with Twitter, we only get their Twitter username and profile pic, no email address, so there won't be any additional picture boxes available for such a user, unless ofcourse the default gravatar and initials pictures are also shown?).

Which brings us to the issue of saving the user's preference. Do we add an additional key in the profile dictionary that specifies a string such as 'twitter', or 'mm', this will also solve #31 since we only have to deal with all the 404s once, and once the user has chosen a suitable profile pic, we only have to return the preferred picture on future loads.

Just a thought, any inputs?

**Comment by rvanhoepen** [comment]
Also, how should the picture boxes be shown? If the user clicks on their own profile pic, does a modal popup, showing all the different options? Or does the developer roll his/her own profile edit page and we only supply a button this is shown below the profile pic (e.g. "Choose a different picture"), and then the modal pops up?
